### PR TITLE
Added missing quotes to event names

### PR DESCRIPTION
**Pull request by jahudzik**

### CODE REVIEW

**Comment by JakeWharton** [comment]
These aren't required. Why should we add them?

**Comment by jahudzik** [comment]
It seems it is required - events don't show up on the page otherwise. Currently none of those I fixed appear in Past events list.

There already have been some commits fixing single events (like [that one](https://github.com/AndroidStudyGroup/conferences/commit/c5963a280f9146152463a4483972f1aeeb29ed08)), here I'm fixing the rest.

**Comment by jahudzik** [comment]
... required at least for the names with space. For the single-word names it works fine even without the quotes.

**Comment by cketti** [comment]
It's not the unquoted strings. Those files contain a UTF-8 BOM and seem to be ignored by Jekyll.
See https://github.com/jekyll/jekyll/issues/308

**Comment by JakeWharton** [comment]
Thanks! Merged the BOM fix.

**Pull request closed without merging**
