### PR TITLE
Adding Kotlin DevRoom @ FOSDEM 2021

### PR DESCRIPTION
**Pull request by cortinico**

### CODE REVIEW

**Comment by cortinico** [comment]
Perhaps we could link instead this page:
https://fosdem.org/2021/schedule/tracks/
However the Kotlin DevRoom CFP is not linked yet.

**Comment by cketti** [comment]
Procrastinating worked out fine :wink:  The DevRoom page is now available: https://fosdem.org/2021/schedule/track/kotlin/

**Comment by nisrulz** [comment]
Should be linked to CFP link directly 🤔 : https://lists.fosdem.org/pipermail/fosdem/2020q4/003130.html

**Comment by nisrulz** [comment]
> Should be linked to CFP link directly 🤔 : https://lists.fosdem.org/pipermail/fosdem/2020q4/003130.html

My bad, just found out the one in the diff is this same one. All good 👍🏼

**Review by cketti — APPROVED** [review]

**Pull request merged**
