### PR TITLE
Adding Comcast Mobile Dev Conference for 2022

### PR DESCRIPTION
**Pull request by ndipatri**

### CODE REVIEW

**Comment by cortinico** [comment]
@cketti what's your take here?

**Comment by cketti** [comment]
Including the name of the company in the conference name makes it sound like a marketing event. It doesn't look like they're paying speakers. 
I'd hate for this to become the new normal for developer conferences. But it could still provide value to mobile developers. So I don't mind if we include this in the calendar.

**Comment by ndipatri** [comment]
Greetings,

I agree with you sentiments.  We pushed for the company name to not be in
the title, but alas, the conference is free and we are not paying
speakers.. We are helping some speakers with expenses, however.  The
conference committee is full of folks who are involved in the many
wonderful community driven conferences such as DroidCon.  So don't worry,
serving the dev community is our top priority.

Thanks!

Nick DiPatri

**Comment by ndipatri** [comment]
@cortinico @cketti Hello folks :-) any chance I can get this approved today! Thanks!

**Review by cortinico — APPROVED** [review]
I think it's safe to merge this. We had in the past other corp-sponsored events (e.g. Google I/O). I've checked the website of the conference and it looks good to me to add 👍

**Pull request merged**
