### PR TITLE
[+] Facebook F8 2020

### PR DESCRIPTION
**Pull request by dayanruben**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is this a mobile conference? I don't pay attention to Facebook.

**Comment by dayanruben** [comment]
F8 is not a mobile-focused conference but always has some interesting talks from the Mobile Engineering teams at Facebook.

**Comment by JakeWharton** [comment]
Thanks!

**Comment by dayanruben** [comment]
You're welcome!

**Pull request merged**
