### PR TITLE
Add CodeAid 2021

### PR DESCRIPTION
**Pull request by sagar-viradiya**

### CODE REVIEW

**Review by RivuChk — APPROVED** [review]

**Review by PiyushZomato — APPROVED** [review]

**Review by cortinico — APPROVED** [review]

**Comment by cketti** [comment]
Some of the things I noticed while checking out this event:
- The website is a bit light on details. The text mentions "all over the country", but it's never mentioned which country that is. A similar thing in the sessionize description.
- I have no idea what the "Hemkunt Foundation" is. It would have been helpful if the CodeAid website linked to their website.
- The sessionize page mentions a code of conduct, but I couldn't find it anywhere.
- Right now it's hard to tell who's behind this. Maybe include a list of organizers/supporters on the website to lend credibility to the event.
- I'm not sure who the target audience is. If the event is mainly targeted at Indian developers it would be nice if that was mentioned somewhere. If not, it would be nice if the website included more context, e.g. more information on what the fundraiser is about.

**Comment by cortinico** [comment]
> Some of the things I noticed while checking out this event:

Good points @cketti. I'm also in for reverting the merge and hold on till we receive a feedback on those points.

I merged as the CFP had a specific Android track and it looked legit to me. But yeah definitely having a bit more details would be helpful.

**Comment by cketti** [comment]
> I'm also in for reverting the merge and hold on till we receive a feedback on those points.

Nah, I think it's fine. I'm guessing the event was thrown together quickly and more details will end up on the website soon.

**Comment by sagar-viradiya** [comment]
@cketti @cortinico Thanks for the feedback. We will work on all suggested points and get back.

**Comment by sagar-viradiya** [comment]
@cortinico @cketti All points have been addressed except last point on targeted audience. Since it is open for all we haven't mentioned that. Also website has short description on fundraiser.

**Comment by cortinico** [comment]
Great @sagar-viradiya, thanks for following up 👍

**Pull request merged**
