### PR TITLE
adding Confitura 2015 conference in Warsaw, Poland

### PR DESCRIPTION
**Pull request by pwittchen**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is there a mobile track or talks about Android at this conference? Nothing jumped out at me on the conference site.

**Comment by pwittchen** [comment]
Actually it's a Java conference and currently I don't see any Android talks in the agenda. I've created this PR, because in description of the repository is information about Android & Java conferences.

**Comment by JakeWharton** [comment]
If they add a mobile track or have a few Android talks then I think we could add it, but at this time we're focusing on conferences for Android developers. We do say Android & Java but what we're thinking is Java conferences like Devoxx but that have a mobile track.

**Comment by JakeWharton** [comment]
I'll update the description to clarify that point.

**Comment by pwittchen** [comment]
OK. I understand.

**Pull request closed without merging**
