### PR TITLE
update cfp for riga dev days

### PR DESCRIPTION
**Pull request by echoAlexey**
update cfp dates

### CODE REVIEW

**Comment by JakeWharton** [comment]
Is there a `cfp_link` you can add too? The CFP indicator won't show without a link.

**Comment by echoAlexey** [comment]
Added cfp_site. Is that correct? I though it defaulted to website if absent

**Comment by NightlyNexus** [comment]
IIRC, the indicator doesn't show up without the dates. The link defaults to the site, but it's great to have a direct link to the CFP!
LGTM!

**Comment by echoAlexey** [comment]
Thank you

**Pull request merged**
