### PR TITLE
Adding Dach Fest

### PR DESCRIPTION
**Pull request by cortinico**
DACH == Deutschland Austria Switzerland (CH).
This is going to be the first devfest of all the GDG communities in the german speaking countries

### CODE REVIEW

**Comment by JakeWharton** [comment]
In the past we've required devfest's with custom names to still use "DevFest" because it's more recognizable than something custom

**Comment by cortinico** [comment]
Makes sense ;)
Changed to `GDG DACH DevFest`

**Comment by blipinsk** [comment]
@cortinico is there a reason why the website is the twitter profile and not https://www.dachfest.com

**Comment by cortinico** [comment]
@blipinsk Yup. The reason is that when I first added this conference, the website was still unknown

**Pull request merged**
