### PR TITLE
Added Android Developer Conference

### PR DESCRIPTION
**Pull request by vonguard**
Hope I did everything right...

### CODE REVIEW

**Comment by JakeWharton** [comment]
It looks like you saved an RTF file not a text file.

**Comment by vonguard** [comment]
Annnnnd .txt

**Comment by vonguard** [comment]
Sorry for confusion. It's .txt now.

**Comment by vonguard** [comment]
OK, clearly saving this file as a .txt in Windows Word Pad is not working.... Anyone got a suggestion for an app that can output a proper utf-8 .txt file from windows, or do I have to go find a Linux machine...

**Comment by JakeWharton** [comment]
Sublime Text

**Comment by vonguard** [comment]
Thanks.... Sublime-made .txt. Hopefully that should be it. Thank you for being patient.

**Comment by JakeWharton** [comment]
Squashed and merged manually. Thanks!

**Pull request closed without merging**
