### PR TITLE
Add CFP for Mobilization

### PR DESCRIPTION
**Pull request by tasza**
Updated the details for Mobilization with CFP.

### CODE REVIEW

**Comment by stkent** [comment]
Need to remove the trailing slash from the URL :)

**Comment by tasza** [comment]
Done. I am not 100% why, though :) Could you tell me, so that I learn? Thanks!

**Comment by stkent** [comment]
I'm not 100% sure on the underlying cause, I just noticed that the bitly link took me here if I included the trailing slash:

screen shot 2017-07-03 at 10 38 05 am

**Comment by tasza** [comment]
Ha, that's a nice catch! :) Thanks for following the link then!
I thought I broke some convention, I had no idea the link was wrong, I am sorry.

**Comment by stkent** [comment]
No worries! Catching things like that is what pull requests are for :)

**Pull request merged**
